// Provincias españolas
export default [
  { provincia: "Álava" },
  { provincia: "Albacete" },
  { provincia: "Alicante" },
  { provincia: "Almería" },
  { provincia: "Asturias" },
  { provincia: "Ávila" },
  { provincia: "Badajoz" },
  { provincia: "Barcelona" },
  { provincia: "Burgos" },
  { provincia: "Cáceres" },
  { provincia: "Cádiz" },
  { provincia: "Cantabria" },
  { provincia: "Castellón" },
  { provincia: "Ciudad Real" },
  { provincia: "Córdoba" },
  { provincia: "La Coruña" },
  { provincia: "Cuenca" },
  { provincia: "Gerona" },
  { provincia: "Granada" },
  { provincia: "Guadalajara" },
  { provincia: "Guipúzcoa" },
  { provincia: "Huelva" },
  { provincia: "Huesca" },
  { provincia: "Islas Baleares" },
  { provincia: "Jaén" },
  { provincia: "León" },
  { provincia: "Lérida" },
  { provincia: "Lugo" },
  { provincia: "Madrid" },
  { provincia: "Málaga" },
  { provincia: "Murcia" },
  { provincia: "Navarra" },
  { provincia: "Orense" },
  { provincia: "Palencia" },
  { provincia: "Las Palmas" },
  { provincia: "Pontevedra" },
  { provincia: "La Rioja" },
  { provincia: "Salamanca" },
  { provincia: "Segovia" },
  { provincia: "Sevilla" },
  { provincia: "Soria" },
  { provincia: "Tarragona" },
  { provincia: "Santa Cruz de Tenerife" },
  { provincia: "Teruel" },
  { provincia: "Toledo" },
  { provincia: "Valencia" },
  { provincia: "Valladolid" },
  { provincia: "Vizcaya" },
  { provincia: "Zamora" },
  { provincia: "Zaragoza" },
];
